// TODO: Code below was largely generated by gpt-4, can likely be improved

function splitContentAtSentence(content: string, maxLength: number): string[] {
  const sentences = content.match(/[^.!?]+[.!?]+(?:\s|$)/g) || [];
  const chunks: string[] = [];
  let currentChunk = '';

  for (const sentence of sentences) {
    if (currentChunk.length + sentence.length <= maxLength) {
      currentChunk += sentence;
    } else {
      chunks.push(currentChunk);
      currentChunk = sentence;
    }
  }

  if (currentChunk) {
    chunks.push(currentChunk);
  }

  return chunks;
}

export function extractTextSections(text: string, maxLength: number) {
  const sections: string[] = [];

  // Split the raw text content into sections based on the maxLength
  const splitContent = splitContentAtSentence(text, maxLength);
  splitContent.forEach(chunk => {
    sections.push(chunk);
  });

  return sections;
}
